# Generated by Django 5.2 on 2025-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JARVIS', '0003_remove_embedding_jarvis_embe_documen_a8ed03_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('mot_de_pasee', models.CharField(max_length=50)),
            ],
        ),
    ]
