# Generated by Django 5.2 on 2025-06-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JARVIS', '0004_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
